import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import worker from '../worker/src/index.js';

const health = await worker.fetch(new Request('https://moments.example/api/health'), {});
const healthBody = await health.json();
assert.equal(healthBody.data.phase, 7);

const footer = await readFile(new URL('../front/components/Footer.vue', import.meta.url), 'utf8');
assert.match(footer, /v-html="sysConfig\.beiAnNo"/);
const settings = await readFile(new URL('../front/pages/sys/settings.vue', import.meta.url), 'utf8');
assert.doesNotMatch(settings, /备案信息（安全 HTML）|允许 a、span/);
assert.match(settings, /是否启用 Cloudflare 人机验证/);
assert.match(settings, /用户名（即发件邮箱）/);
assert.match(settings, /密码 \/ 授权码/);
assert.doesNotMatch(settings, /API 文档|href="\/docs"|to="\/docs"/);
assert.match(settings, /关于页面/);
assert.match(settings, /媒体存储/);
assert.match(settings, /storageType/);
assert.match(settings, /backupTargetOptions/);
assert.match(settings, /s3Storage/);
assert.match(settings, /webdavStorage/);
assert.match(settings, /备份目标/);
assert.match(settings, /本地备份/);
assert.match(settings, /enableD1Backup/);
assert.match(settings, /一键导入/);
assert.match(settings, /exportLocalBackup/);
assert.match(settings, /aboutContent/);
assert.match(footer, />原项目<|>原项目\s*</);
assert.match(footer, /Cloudflare 版/);
assert.doesNotMatch(footer, /img\.shields\.io|github\/stars/);
const bookPreview = await readFile(new URL('../front/components/DoubanBookPreview.vue', import.meta.url), 'utf8');
const moviePreview = await readFile(new URL('../front/components/DoubanMoviePreview.vue', import.meta.url), 'utf8');
assert.match(bookPreview, /douban-cover/);
assert.match(moviePreview, /douban-cover/);
const about = await readFile(new URL('../front/pages/about.vue', import.meta.url), 'utf8');
const timeline = await readFile(new URL('../front/components/TimelineList.vue', import.meta.url), 'utf8');
const userTimeline = await readFile(new URL('../front/pages/user/[id].vue', import.meta.url), 'utf8');
const calendar = await readFile(new URL('../front/pages/user/calendar.vue', import.meta.url), 'utf8');
const music = await readFile(new URL('../front/components/Music.vue', import.meta.url), 'utf8');
const musicPreview = await readFile(new URL('../front/components/MusicPreview.vue', import.meta.url), 'utf8');
assert.match(about, /markdownit\(\{ html: true/);
assert.match(about, /enableAbout/);
assert.match(timeline, /朋友圈时间轴/);
assert.match(userTimeline, /viewMode = ref<'timeline' \| 'cards'>\('timeline'\)/);
assert.match(calendar, /时间轴排列/);
assert.match(music, /直链播放/);
assert.match(music, /滚动歌词（LRC）/);
assert.match(musicPreview, /mode === 'direct'/);
assert.match(musicPreview, /new APlayer/);
assert.match(musicPreview, /lrcType: props\.lrc \? 2 : 0/);
assert.doesNotMatch(musicPreview, /\{\{ lrc \|\| '' \}\}/);
const layoutDefault = await readFile(new URL('../front/layouts/default.vue', import.meta.url), 'utf8');
assert.match(layoutDefault, /runCustomJs/);
assert.match(layoutDefault, /router\.afterEach/);
assert.doesNotMatch(layoutDefault, /innerHTML: sysConfigVO\.js/);
const migrationPage = await readFile(new URL('../front/pages/sys/migration.vue', import.meta.url), 'utf8');
const migrationScript = await readFile(new URL('../scripts/migrate/build-package.py', import.meta.url), 'utf8');
assert.match(migrationPage, /一键导入/);
assert.match(migrationPage, /DecompressionStream/);
assert.match(migrationPage, /\/admin\/migration\/preflight/);
assert.match(migrationPage, /\/admin\/migration\/finish/);
assert.match(migrationPage, /uploadFile\(file/);
assert.match(migrationScript, /moments-cf-migration/);
assert.match(migrationScript, /packageId/);
assert.match(migrationScript, /row\.pop\("password"/);
const upload = await readFile(new URL('../front/utils/upload.ts', import.meta.url), 'utf8');
assert.match(upload, /500 \* 1024 \* 1024/);
assert.match(upload, /imageThumbnail/);
assert.match(upload, /\/file\/direct\/init/);
assert.match(upload, /\/file\/exist\?sha256=/);

const source = await readFile(new URL('../worker/src/index.js', import.meta.url), 'utf8');
assert.match(source, /\/api\/admin\/backup\/export/);
assert.match(source, /enableD1Backup === false/);
assert.match(source, /\/api\/user\/status\/set/);
assert.match(source, /\/api\/user\/status\/clear/);
assert.match(source, /\/api\/user\/status\/get/);
assert.match(source, /BUILTIN_STATUSES/);
assert.match(source, /attachStatuses/);
const statusIcon = await readFile(new URL('../front/components/StatusIcon.vue', import.meta.url), 'utf8');
assert.match(statusIcon, /美滋滋/);
assert.match(statusIcon, /摸鱼/);
assert.match(statusIcon, /持续时间/);
assert.match(statusIcon, /\/user\/status\/set/);
for (const route of ['/api/file/direct/init', '/api/file/direct/complete', '/api/admin/backup/create', '/api/admin/backup/list', '/api/admin/backup/download', '/api/admin/backup/restore']) assert.ok(source.includes(route));
assert.match(source, /async scheduled/);
assert.match(source, /renderRssDescription/);
assert.match(source, /sendNotification/);
assert.match(source, /serveDoubanCover/);
assert.match(source, /rexxar\/api\/v2\/movie/);
assert.match(source, /parseDoubanMovieJson/);
assert.match(source, /verifyTurnstileToken/);
assert.match(source, /redirect: 'manual'/);
assert.match(source, /previousConfig\.turnstileSecretKey/);
assert.match(source, /previousConfig\.googleSecretKey/);
assert.match(source, /config\.smtpPasswordEncrypted = previousConfig\.smtpPasswordEncrypted/);
assert.match(source, /turnstileSecretKeyConfigured/);
assert.match(source, /enableAbout/);
assert.doesNotMatch(source, /aboutContent = sanitizeSafeHtml/);
assert.match(source, /config.aboutContent = String\(body.aboutContent/);
assert.match(source, /backupIntervalDays = clampInt/);
assert.match(source, /backupRetentionDays = clampInt/);
assert.match(source, /async scheduled/);
assert.match(source, /\/api\/admin\/migration\/preflight/);
assert.match(source, /\/api\/admin\/migration\/prepare/);
assert.match(source, /\/api\/admin\/migration\/import/);
assert.match(source, /\/api\/admin\/migration\/finish/);
assert.match(source, /\/api\/admin\/migration\/backup\/status/);
assert.match(source, /startD1Export/);
assert.match(source, /pollD1Export/);
assert.match(source, /storeD1Backup/);
assert.match(migrationPage, /\/admin\/migration\/backup\/status/);
assert.match(migrationPage, /skipBackup/);
assert.match(source, /body\?\.skipBackup === true/);
assert.match(source, /\/api\/admin\/migration\/fail/);
assert.match(source, /migration_items/);
assert.match(source, /旧用户密码不会迁移/);
assert.match(source, /passwordHash\(randomToken\(32\)\)/);
assert.match(source, /const keys = \['title','favicon'/);
assert.match(source, /mode: 'direct'/);
assert.doesNotMatch(source, /openApiDocument|openApiHtml|\/openapi\.json/);
const captcha = await readFile(new URL('../front/composables/useHumanVerification.ts', import.meta.url), 'utf8');
assert.match(captcha, /enableTurnstile/);
assert.match(captcha, /turnstileToken/);
assert.match(captcha, /interaction-only/);
assert.match(captcha, /role', 'dialog/);

const backendMain = await readFile(new URL('../backend/main.go', import.meta.url), 'utf8');
const backendRouter = await readFile(new URL('../backend/router.go', import.meta.url), 'utf8');
const readme = await readFile(new URL('../README.md', import.meta.url), 'utf8');
assert.doesNotMatch(backendMain + backendRouter, /swagger|echoSwagger|\/docs/i);
assert.match(readme, /## API 使用说明/);
assert.match(readme, /\/api\/memo\/list/);
const template = await readFile(new URL('../worker/wrangler.toml.template', import.meta.url), 'utf8');
assert.match(template, /crons = \["0 3 \* \* SUN"\]/);
assert.match(template, /R2_BUCKET_NAME/);
assert.match(template, /binding = "ASSETS"/);
console.log('Phase 7 integration tests: PASS');
