import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import worker from '../worker/src/index.js';

const health = await worker.fetch(new Request('https://moments.example/api/health'), {});
const healthBody = await health.json();
assert.equal(healthBody.data.phase, 7);

const footer = await readFile(new URL('../front/components/Footer.vue', import.meta.url), 'utf8');
assert.match(footer, /v-html="sysConfig\.beiAnNo"/);
const settings = await readFile(new URL('../front/pages/sys/settings.vue', import.meta.url), 'utf8');
assert.doesNotMatch(settings, /备案信息（安全 HTML）|允许 a、span/);
assert.match(settings, /是否启用 Cloudflare 人机验证/);
assert.match(settings, /用户名（即发件邮箱）/);
assert.match(settings, /密码 \/ 授权码/);
assert.doesNotMatch(settings, /API 文档|href="\/docs"|to="\/docs"/);
assert.match(settings, /关于页面/);
assert.match(settings, /媒体存储/);
assert.match(settings, /storageType/);
assert.match(settings, /backupTargetOptions/);
assert.match(settings, /友情链接申请与须知/);
assert.match(settings, /friendNotice/);
assert.match(settings, /friendEmail/);
assert.match(settings, /s3Storage/);
assert.match(settings, /webdavStorage/);
assert.match(settings, /备份目标/);
assert.match(settings, /本地备份/);
assert.match(settings, /enableD1Backup/);
assert.match(settings, /一键导入/);
assert.match(settings, /exportLocalBackup/);
assert.match(settings, /aboutContent/);
const friendPage = await readFile(new URL('../front/pages/friend.vue', import.meta.url), 'utf8');
assert.match(friendPage, /友情链接申请与须知/);
assert.match(friendPage, /sendApply/);
assert.match(friendPage, /friendNotice/);
assert.match(friendPage, /mailto:/);
assert.match(footer, />原项目<|>原项目\s*</);
assert.match(footer, /Cloudflare 版/);
assert.doesNotMatch(footer, /img\.shields\.io|github\/stars/);
const bookPreview = await readFile(new URL('../front/components/DoubanBookPreview.vue', import.meta.url), 'utf8');
const moviePreview = await readFile(new URL('../front/components/DoubanMoviePreview.vue', import.meta.url), 'utf8');
assert.match(bookPreview, /douban-cover/);
assert.match(moviePreview, /douban-cover/);
const about = await readFile(new URL('../front/pages/about.vue', import.meta.url), 'utf8');
const timeline = await readFile(new URL('../front/components/TimelineList.vue', import.meta.url), 'utf8');
const userTimeline = await readFile(new URL('../front/pages/user/[id].vue', import.meta.url), 'utf8');
const tagTimeline = await readFile(new URL('../front/pages/tags/[username]/[tag].vue', import.meta.url), 'utf8');
const calendar = await readFile(new URL('../front/pages/user/calendar.vue', import.meta.url), 'utf8');
// 翻页回归：首页、用户页、标签页、日历页必须防止并发重复请求，失败不提前推进页码，旧 reload 结果不能覆盖新状态。
const memoDetailForBus = await readFile(new URL('../front/pages/memo/[id].vue', import.meta.url), 'utf8');
const indexPageForBus = await readFile(new URL('../front/pages/index.vue', import.meta.url), 'utf8');
// 事件总线回归：所有注册的监听必须保存取消函数，并在页面卸载时移除。
for (const page of [indexPageForBus, userTimeline, tagTimeline, calendar, memoDetailForBus]) {
  const reloadSubscriptions = (page.match(/memoReloadEvent\.on/g) || []).length;
  const changedSubscriptions = (page.match(/memoChangedEvent\.on/g) || []).length;
  assert.ok(reloadSubscriptions + changedSubscriptions > 0 ? page.includes('onBeforeUnmount') : true);
  if (reloadSubscriptions) assert.match(page, /stopMemoReload/);
  if (changedSubscriptions) assert.match(page, /stopMemoChanged/);
}
for (const page of [indexPageForBus, userTimeline, tagTimeline, calendar]) {
  assert.match(page, /const loading = ref\(false\)/);
  assert.match(page, /let requestGeneration = 0/);
  assert.match(page, /if \(loading\.value \|\| !hasNext\.value\) return/);
  assert.match(page, /const page = state\.page \+ 1/);
  assert.match(page, /state\.page = page/);
  assert.match(page, /const mergeMemos =/);
  assert.match(page, /incoming\.filter\(memo => !existing\.has\(memo\.id\)\)/);
  assert.match(page, /if \(generation !== requestGeneration\) return/);
}
const music = await readFile(new URL('../front/components/Music.vue', import.meta.url), 'utf8');
const musicPreview = await readFile(new URL('../front/components/MusicPreview.vue', import.meta.url), 'utf8');
assert.match(about, /markdownit\(\{ html: true/);
assert.match(about, /enableAbout/);
assert.match(timeline, /朋友圈时间轴/);
assert.match(userTimeline, /viewMode = ref<'timeline' \| 'cards'>\('timeline'\)/);
assert.match(userTimeline, /Promise\.all\(\[/, '用户空间应并行加载资料与动态');
assert.match(userTimeline, /\/user\/profileById\?id=\$\{userId\}/, '用户空间应按 ID 独立加载资料，不依赖首条动态');
assert.match(calendar, /时间轴排列/);
assert.match(music, /直链播放/);
assert.match(music, /滚动歌词（LRC）/);
assert.match(musicPreview, /mode === 'direct'/);
assert.match(musicPreview, /new APlayer/);
assert.match(musicPreview, /lrcType: props\.lrc \? 2 : 0/);
assert.match(musicPreview, /lrc: props\.lrc \|\| ''/);
assert.match(music, /overflow-y-auto/);
assert.doesNotMatch(musicPreview, /\{\{ lrc \|\| '' \}\}/);
const layoutDefault = await readFile(new URL('../front/layouts/default.vue', import.meta.url), 'utf8');
assert.match(layoutDefault, /runCustomJs/);
assert.match(layoutDefault, /router\.afterEach/);
assert.doesNotMatch(layoutDefault, /innerHTML: sysConfigVO\.js/);
const migrationPage = await readFile(new URL('../front/pages/sys/migration.vue', import.meta.url), 'utf8');
const migrationScript = await readFile(new URL('../scripts/migrate/build-package.py', import.meta.url), 'utf8');
assert.match(migrationPage, /一键导入/);
assert.match(migrationPage, /DecompressionStream/);
assert.match(migrationPage, /\/admin\/migration\/preflight/);
assert.match(migrationPage, /\/admin\/migration\/finish/);
assert.match(migrationPage, /uploadFile\(file/);
assert.match(migrationScript, /moments-cf-migration/);
assert.match(migrationScript, /packageId/);
assert.match(migrationScript, /row\.pop\("password"/);
const upload = await readFile(new URL('../front/utils/upload.ts', import.meta.url), 'utf8');
assert.match(upload, /500 \* 1024 \* 1024/);
assert.match(upload, /imageThumbnail/);
assert.match(upload, /\/file\/direct\/init/);
assert.match(upload, /\/file\/exist\?sha256=/);

const source = await readFile(new URL('../worker/src/index.js', import.meta.url), 'utf8');
assert.match(source, /\/api\/admin\/backup\/export/);
assert.match(source, /enableD1Backup === false/);
assert.match(source, /sendTelegram/);
assert.match(source, /telegram_chat_id/);
assert.match(source, /enableTelegram === true/);
assert.match(settings, /Telegram 评论通知/);
assert.match(settings, /telegramBotToken/);
assert.match(settings, /telegramBotUsername/);
const userSettings = await readFile(new URL('../front/pages/user/settings.vue', import.meta.url), 'utf8');
// 登录态持久化回归：global 的 get 必须直接返回 storage.value 引用，
// 否则属性赋值不会触发 useStorage deep watch 写回 localStorage，刷新后登录态丢失。
const storeSource = await readFile(new URL('../front/store.ts', import.meta.url), 'utf8');
assert.match(storeSource, /get: \(\) => \{\s*const value = storage\.value/);
assert.doesNotMatch(storeSource, /get: \(\) => \(\{ userinfo: \{\}, \.\.\.\(storage\.value/);
assert.match(userSettings, /Telegram User ID/);
// 静态 SEO meta：爬虫（Bing）不执行 JS，index.html 必须预置 description/title/og
const siteConfig = await readFile(new URL('../front/site.config.ts', import.meta.url), 'utf8');
assert.match(siteConfig, /description: '极简朋友圈 - 记录生活的每个瞬间/);
assert.match(siteConfig, /title: '极简朋友圈'/);
const nuxtConfig = await readFile(new URL('../front/nuxt.config.ts', import.meta.url), 'utf8');
assert.match(nuxtConfig, /import site from '\.\/site\.config'/);
assert.match(nuxtConfig, /name: "description", content: site\.description/);
assert.match(nuxtConfig, /title: site\.title/);
assert.match(nuxtConfig, /property: "og:image", content: site\.ogImage/);
assert.match(nuxtConfig, /name: "twitter:card", content: "summary"/);
assert.match(layoutDefault, /import site from "~\/site\.config"/);
assert.match(layoutDefault, /site\.description/, 'slogan 为空时应回退默认 description');
assert.match(layoutDefault, /site\.title/, 'title 为空时应回退默认 title');
assert.match(about, /site\.title/);
assert.match(userSettings, /telegramChatId/);
assert.match(userSettings, /telegramBotUsername/);
assert.match(source, /\/api\/user\/status\/set/);
assert.match(source, /\/api\/user\/status\/clear/);
assert.match(source, /\/api\/user\/status\/get/);
assert.match(source, /BUILTIN_STATUSES/);
assert.match(source, /attachStatuses/);
const statusIcon = await readFile(new URL('../front/components/StatusIcon.vue', import.meta.url), 'utf8');
assert.match(statusIcon, /美滋滋/);
assert.match(statusIcon, /摸鱼/);
assert.match(statusIcon, /持续时间/);
assert.match(statusIcon, /\/user\/status\/set/);
for (const route of ['/api/file/direct/init', '/api/file/direct/complete', '/api/admin/backup/create', '/api/admin/backup/list', '/api/admin/backup/download', '/api/admin/backup/restore']) assert.ok(source.includes(route));
assert.match(source, /async scheduled/);
assert.match(source, /renderRssDescription/);
assert.match(source, /sendNotification/);
assert.match(source, /serveDoubanCover/);
assert.match(source, /rexxar\/api\/v2\/movie/);
assert.match(source, /parseDoubanMovieJson/);
assert.match(source, /verifyTurnstileToken/);
assert.match(source, /redirect: 'manual'/);
assert.match(source, /previousConfig\.turnstileSecretKey/);
assert.match(source, /previousConfig\.googleSecretKey/);
assert.match(source, /config\.smtpPasswordEncrypted = previousConfig\.smtpPasswordEncrypted/);
assert.match(source, /turnstileSecretKeyConfigured/);
assert.match(source, /enableAbout/);
assert.doesNotMatch(source, /aboutContent = sanitizeSafeHtml/);
assert.match(source, /config.aboutContent = String\(body.aboutContent/);
assert.match(source, /backupIntervalDays = clampInt/);
assert.match(source, /backupRetentionDays = clampInt/);
assert.match(source, /const retentionDays = clampInt\(config\.backupRetentionDays, 1, 3650, 90\);\n  const target = storageConfig\.backupTarget/);
assert.match(source, /const retentionDays = clampInt\(config\.backupRetentionDays, 1, 3650, 90\);\n  await createD1Backup\(env, \{\}, retentionDays/);
assert.match(source, /async scheduled/);
assert.match(source, /\/api\/admin\/migration\/preflight/);
assert.match(source, /\/api\/admin\/migration\/prepare/);
assert.match(source, /\/api\/admin\/migration\/import/);
assert.match(source, /\/api\/admin\/migration\/finish/);
assert.match(source, /\/api\/admin\/migration\/backup\/status/);
assert.match(source, /startD1Export/);
assert.match(source, /pollD1Export/);
assert.match(source, /storeD1Backup/);
assert.match(migrationPage, /\/admin\/migration\/backup\/status/);
assert.match(migrationPage, /skipBackup/);
assert.match(source, /body\?\.skipBackup === true/);
assert.match(source, /\/api\/admin\/migration\/fail/);
assert.match(source, /migration_items/);
assert.match(source, /迁移缺少服务端预检记录/);
assert.match(source, /completedCounts/);
assert.match(source, /客户端报告完成/);
assert.match(source, /旧用户密码不会迁移/);
assert.match(source, /passwordHash\(randomToken\(32\)\)/);
assert.match(source, /const keys = \['title','favicon'/);
assert.match(source, /mode: 'direct'/);
assert.doesNotMatch(source, /openApiDocument|openApiHtml|\/openapi\.json/);
const captcha = await readFile(new URL('../front/composables/useHumanVerification.ts', import.meta.url), 'utf8');
assert.match(captcha, /enableTurnstile/);
assert.match(captcha, /turnstileToken/);
assert.match(captcha, /interaction-only/);
assert.match(captcha, /role', 'dialog/);

const backendMain = await readFile(new URL('../backend/main.go', import.meta.url), 'utf8');
const backendRouter = await readFile(new URL('../backend/router.go', import.meta.url), 'utf8');
const readme = await readFile(new URL('../README.md', import.meta.url), 'utf8');
assert.doesNotMatch(backendMain + backendRouter, /swagger|echoSwagger|\/docs/i);
assert.match(readme, /## API 使用说明/);
assert.match(readme, /\/api\/memo\/list/);
const template = await readFile(new URL('../worker/wrangler.toml.template', import.meta.url), 'utf8');
assert.match(template, /crons = \["0 3 \* \* SUN"\]/);
assert.match(template, /R2_BUCKET_NAME/);
assert.match(template, /binding = "ASSETS"/);
assert.match(source, /sitemap\.xml/);
assert.match(source, /robots\.txt/);
assert.match(source, /urlset xmlns="http:\/\/www\.sitemaps\.org\/schemas\/sitemap\/0\.9"/);
assert.match(layoutDefault, /og:site_name/);
const gitEditor = await readFile(new URL('../front/components/GitEmbed.vue', import.meta.url), 'utf8');
const gitPreview = await readFile(new URL('../front/components/GitPreview.vue', import.meta.url), 'utf8');
assert.match(gitEditor, /GitHub、GitLab、Gitea、Forgejo、Codeberg/);
assert.match(gitEditor, /嵌入 Git 仓库/);
assert.match(gitEditor, /i-carbon-logo-github/);
assert.match(gitEditor, /\/memo\/preview/);
assert.match(gitEditor, /kind: 'git'/);
assert.match(gitEditor, /立即抓取预览/);
assert.match(gitEditor, /:loading="loading"/);
assert.match(gitPreview, /Git 仓库快照/);
assert.match(gitPreview, /i-carbon-logo-github/);
assert.match(gitPreview, /itemTitle/);
assert.match(gitPreview, /itemState/);
assert.match(gitPreview, /stateText/);
assert.match(gitPreview, /stateClass/);
assert.match(gitPreview, /avatar/);
assert.match(gitPreview, /noopener noreferrer/);
assert.match(gitPreview, /providerLabel/);
const typesSrc = await readFile(new URL('../front/types/index.ts', import.meta.url), 'utf8');
assert.match(typesSrc, /itemTitle\?: string/);
assert.match(typesSrc, /itemState\?: string/);
assert.match(typesSrc, /itemDate\?: string/);
const xEditor = await readFile(new URL('../front/components/XEmbed.vue', import.meta.url), 'utf8');
const xPreview = await readFile(new URL('../front/components/XPreview.vue', import.meta.url), 'utf8');
const memoEdit = await readFile(new URL('../front/components/MemoEdit.vue', import.meta.url), 'utf8');
assert.match(xEditor, /x\.com 或 twitter\.com/);
assert.match(xEditor, /\/memo\/preview/);
assert.match(xEditor, /kind: 'x'/);
assert.match(xEditor, /立即抓取预览/);
assert.match(xEditor, /:loading="loading"/);
assert.match(xPreview, /x-card__header/);
assert.match(xPreview, /authorName/);
assert.match(xPreview, /authorUsername/);
assert.match(xPreview, /x-card__media/);
assert.match(xPreview, /x-media\?url=/);
assert.match(xPreview, /formatCount/);
assert.match(xPreview, /formatDate/);
assert.match(xPreview, /whitespace-nowrap/);
assert.match(xPreview, /在 X 中查看/);
assert.match(xPreview, /loading="lazy"/);
assert.doesNotMatch(xPreview, /<iframe|widgets\.js|Nitter|nitter|CF-IPCountry|sessionStorage/);
assert.match(memoEdit, /X 原帖将在发表时抓取/);
assert.match(memoEdit, /Git 链接将在发表时抓取/);
assert.match(memoEdit, /git-embed/);
assert.match(memoEdit, /updateGit/);
const memoComponent = await readFile(new URL('../front/components/Memo.vue', import.meta.url), 'utf8');
assert.match(memoComponent, /try \{ return JSON\.parse\(props\.memo\.ext/);
assert.match(memoComponent, /catch \{ return \{\} as ExtDTO/);
assert.match(memoEdit, /try \{ return JSON\.parse\(res\.ext\) as ExtDTO \}/);
const memoRefEditor = await readFile(new URL('../front/components/MemoRefEmbed.vue', import.meta.url), 'utf8');
const memoRefPreview = await readFile(new URL('../front/components/MemoRefPreview.vue', import.meta.url), 'utf8');
assert.match(memoRefEditor, /引用站内动态/);
assert.match(memoRefEditor, /\/memo\/preview/);
assert.match(memoRefEditor, /kind: 'memo'/);
assert.ok(memoRefEditor.includes('/memo/{id}'), '应提示 /memo/{id} 格式');
assert.match(memoRefPreview, /NuxtLink/);
assert.match(memoRefPreview, /查看动态/);
assert.match(memoEdit, /memo-ref-embed/);
assert.match(memoEdit, /updateMemoRef/);
assert.match(memoEdit, /memoRef: state\.memoRef\.id \? state\.memoRef : \{\}/);
assert.match(memoComponent, /memo-ref-preview/);
assert.match(memoEdit, /git: state\.git\.url \? state\.git : \{\}/);
assert.match(source, /仅支持 X（Twitter）链接/);
assert.match(source, /parseGitEmbedUrl/);
assert.match(source, /fetchGitSnapshot/);
assert.match(source, /isIpLiteralHost/);
assert.match(source, /parseMemoRefUrl/);
assert.match(source, /memoRefSnapshot/);
assert.match(source, /kind === 'memo'/);
assert.ok(source.includes("\\/memo\\/"), 'Worker 应含 /memo/{id} 正则解析');
assert.match(source, /const hasExt = safeExt\.music\?\.url/);
assert.match(source, /delete safeExt\.memoRef;/);
assert.match(source, /仅可引用已发布的公开动态/);
assert.match(source, /SHA-256 与文件内容不一致/);
assert.match(source, /delete safeExt\.x;/);
assert.match(source, /function validUsername\(value\)/);
assert.match(source, /const adminUserName = validUsername\(requestedAdminUserName\)/);
assert.match(source, /SELECT id FROM users WHERE username=\? AND id<>1/);
assert.match(source, /api\/v1\/repos/);
assert.match(source, /fetchXSnapshot/);
assert.match(source, /cdn\.syndication\.twimg\.com\/tweet-result/);
assert.match(source, /serveXMedia/);
assert.match(source, /url.pathname === '\/x-media'/);
assert.doesNotMatch(source, /status\.d420\.de|healthyNitterInstances|CF-IPCountry|x\/embed\/resolve/);
const memoDetail = await readFile(new URL('../front/pages/memo/[id].vue', import.meta.url), 'utf8');
assert.match(memoDetail, /og:image/);
assert.match(memoDetail, /canonical/);
const catchAll = await readFile(new URL('../front/pages/[...slug].vue', import.meta.url), 'utf8');
assert.match(catchAll, /页面不存在/);
assert.doesNotMatch(catchAll, /isSeoPath|window\.location|sessionStorage|fetch\(raw\)/);
assert.match(template, /run_worker_first = \["\/\*"\]/);
const userDetail = await readFile(new URL('../front/pages/user/[id].vue', import.meta.url), 'utf8');
assert.match(userDetail, /watch\(profile/);
assert.match(userDetail, /canonical/);

// 友链入口在非友链页（关于页/系统页等）均应显示，不限于首页
const headerNav = await readFile(new URL('../front/components/Header.vue', import.meta.url), 'utf8');
assert.match(headerNav, /\$route\.path !== '\/friend'/, '桌面端友链入口应在非友链页显示');
const mobileNav = await readFile(new URL('../front/components/MobileNav.vue', import.meta.url), 'utf8');
assert.match(mobileNav, /\$route\.path !== '\/friend'/, '移动端友链入口应在非友链页显示');

// 加载性能：并行 API、静态资源缓存、音乐按需、图片懒加载
assert.match(source, /url\.pathname\.startsWith\('\/_nuxt\/'\)/, 'Worker 应对 _nuxt 构建产物设置缓存');
assert.match(source, /max-age=31536000, immutable/, '构建产物应永久缓存');
assert.match(layoutDefault, /Promise\.all\(\[\s*useMyFetch/, '首页 profile/sysConfig 应并行请求');
const nuxtConfigSrc = await readFile(new URL('../front/nuxt.config.ts', import.meta.url), 'utf8');
assert.doesNotMatch(nuxtConfigSrc, /APlayer|Meting/, '音乐库不应全局加载');
assert.match(musicPreview, /loadMusicAssets/, '音乐组件应按需加载 APlayer/Meting');
assert.match(musicPreview, /loadMusicAssets/, '音乐组件应按需加载 APlayer/Meting');
const uploadPreviewImg = await readFile(new URL('../front/components/UploadImagePreview.vue', import.meta.url), 'utf8');
assert.match(uploadPreviewImg, /loading="lazy"/, '动态图片应懒加载');
assert.match(uploadPreviewImg, /@error="fallbackToOriginal\(\$event, imageConfig\.url\)"/, '缩略图失败应使用 Vue 事件回退');
assert.match(uploadPreviewImg, /dataset\.fallbackApplied/, '图片回退应避免错误循环');
assert.doesNotMatch(uploadPreviewImg, /:onerror=|javascript:this\.src/, '不得把图片 URL 拼入内联 JavaScript');
const mdUtilsSrc = await readFile(new URL('../front/utils/index.ts', import.meta.url), 'utf8');
assert.match(mdUtilsSrc, /export function loadMusicAssets/, '应导出音乐资源按需加载函数');

// 状态 emoji 与首页加载文案
assert.match(statusIcon, /Emoji v-if="emojiOpen"/, '自定义状态应支持 emoji 选择');
assert.match(statusIcon, /Emoji v-if="emojiOpen"/, '自定义状态应支持 emoji 选择');
assert.match(statusIcon, /customIcon/, '自定义状态应记录 emoji');
const indexPage = indexPageForBus;
assert.match(memoComponent, /const readLikedMemoIds =/, '点赞缓存应统一安全读取');
assert.match(memoComponent, /localStorage\.removeItem\("likeMemos"\)/, '损坏的点赞缓存应自动清理');
assert.equal((memoComponent.match(/JSON\.parse\(localStorage\.getItem\("likeMemos"\)/g) || []).length, 1, '点赞缓存只能在安全读取函数中解析一次');
assert.match(indexPage, /客官勿急 正在加载中…/, '加载中应显示提示文案');
assert.match(indexPage, /const loading = ref\(false\)/, '应有加载状态标记');
console.log('Phase 7 integration tests: PASS');
