import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import worker from '../worker/src/index.js';

const health = await worker.fetch(new Request('https://moments.example/api/health'), {});
const healthBody = await health.json();
assert.equal(healthBody.data.phase, 7);

const footer = await readFile(new URL('../front/components/Footer.vue', import.meta.url), 'utf8');
assert.match(footer, /v-html="sysConfig\.beiAnNo"/);
const settings = await readFile(new URL('../front/pages/sys/settings.vue', import.meta.url), 'utf8');
assert.doesNotMatch(settings, /备案信息（安全 HTML）|允许 a、span/);
assert.match(settings, /是否启用 Cloudflare 人机验证/);
assert.match(settings, /用户名（即发件邮箱）/);
assert.match(settings, /密码 \/ 授权码/);
assert.doesNotMatch(settings, /API 文档|href="\/docs"|to="\/docs"/);
assert.match(settings, /关于页面/);
assert.match(settings, /aboutContent/);
assert.match(footer, />原项目<|>原项目\s*</);
assert.match(footer, /Cloudflare 版/);
assert.doesNotMatch(footer, /img\.shields\.io|github\/stars/);
const bookPreview = await readFile(new URL('../front/components/DoubanBookPreview.vue', import.meta.url), 'utf8');
const moviePreview = await readFile(new URL('../front/components/DoubanMoviePreview.vue', import.meta.url), 'utf8');
assert.match(bookPreview, /douban-cover/);
assert.match(moviePreview, /douban-cover/);
const about = await readFile(new URL('../front/pages/about.vue', import.meta.url), 'utf8');
const timeline = await readFile(new URL('../front/components/TimelineList.vue', import.meta.url), 'utf8');
const userTimeline = await readFile(new URL('../front/pages/user/[id].vue', import.meta.url), 'utf8');
const calendar = await readFile(new URL('../front/pages/user/calendar.vue', import.meta.url), 'utf8');
const music = await readFile(new URL('../front/components/Music.vue', import.meta.url), 'utf8');
const musicPreview = await readFile(new URL('../front/components/MusicPreview.vue', import.meta.url), 'utf8');
assert.match(about, /markdownit\(\{ html: true/);
assert.match(about, /enableAbout/);
assert.match(timeline, /朋友圈时间轴/);
assert.match(userTimeline, /viewMode = ref<'timeline' \| 'cards'>\('timeline'\)/);
assert.match(calendar, /时间轴排列/);
assert.match(music, /直链播放/);
assert.match(music, /滚动歌词（LRC）/);
assert.match(musicPreview, /mode === 'direct'/);
const upload = await readFile(new URL('../front/utils/upload.ts', import.meta.url), 'utf8');
assert.match(upload, /500 \* 1024 \* 1024/);
assert.match(upload, /imageThumbnail/);
assert.match(upload, /\/file\/direct\/init/);
assert.match(upload, /\/file\/exist\?sha256=/);

const source = await readFile(new URL('../worker/src/index.js', import.meta.url), 'utf8');
for (const route of ['/api/file/direct/init', '/api/file/direct/complete', '/api/admin/backup/create', '/api/admin/backup/list', '/api/admin/backup/download', '/api/admin/backup/restore']) assert.ok(source.includes(route));
assert.match(source, /async scheduled/);
assert.match(source, /renderRssDescription/);
assert.match(source, /sendNotification/);
assert.match(source, /serveDoubanCover/);
assert.match(source, /rexxar\/api\/v2\/movie/);
assert.match(source, /parseDoubanMovieJson/);
assert.match(source, /verifyTurnstileToken/);
assert.match(source, /redirect: 'manual'/);
assert.match(source, /previousConfig\.turnstileSecretKey/);
assert.match(source, /previousConfig\.googleSecretKey/);
assert.match(source, /config\.smtpPasswordEncrypted = previousConfig\.smtpPasswordEncrypted/);
assert.match(source, /turnstileSecretKeyConfigured/);
assert.match(source, /enableAbout/);
assert.match(source, /aboutContent = sanitizeSafeHtml/);
assert.match(source, /mode: 'direct'/);
assert.doesNotMatch(source, /openApiDocument|openApiHtml|\/openapi\.json/);
const captcha = await readFile(new URL('../front/composables/useHumanVerification.ts', import.meta.url), 'utf8');
assert.match(captcha, /enableTurnstile/);
assert.match(captcha, /turnstileToken/);
assert.match(captcha, /interaction-only/);
assert.match(captcha, /role', 'dialog/);

const backendMain = await readFile(new URL('../backend/main.go', import.meta.url), 'utf8');
const backendRouter = await readFile(new URL('../backend/router.go', import.meta.url), 'utf8');
const readme = await readFile(new URL('../README.md', import.meta.url), 'utf8');
assert.doesNotMatch(backendMain + backendRouter, /swagger|echoSwagger|\/docs/i);
assert.match(readme, /## API 使用说明/);
assert.match(readme, /\/api\/memo\/list/);
const template = await readFile(new URL('../worker/wrangler.toml.template', import.meta.url), 'utf8');
assert.match(template, /crons = \["0 3 \* \* SUN"\]/);
assert.match(template, /R2_BUCKET_NAME/);
assert.match(template, /binding = "ASSETS"/);
console.log('Phase 7 integration tests: PASS');
