<template>
  <main class="mx-auto max-w-6xl px-4 pb-16 pt-10"><Header :user="currentUser"/><div class="mb-8 flex items-end justify-between gap-4"><div><p class="eyebrow">COLLECTION</p><h1 class="text-3xl font-bold">{{ album?.name || '图集' }}</h1><p class="mt-2 text-sm text-zinc-500">{{ album?.description }}</p></div><NuxtLink to="/photos" class="text-sm text-[#78943f]">返回照片墙</NuxtLink></div><div v-if="loading" class="py-20 text-center text-sm text-zinc-500">正在加载…</div><div v-else-if="!photos.length" class="rounded-2xl border border-dashed p-12 text-center text-sm text-zinc-500">这个图集还没有照片</div><div v-else class="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4"><a v-for="photo in photos" :key="photo.id" :href="photo.url" target="_blank" rel="noopener noreferrer" class="aspect-square overflow-hidden rounded-2xl bg-zinc-100 dark:bg-zinc-800"><img :src="photo.thumbUrl || photo.url" :alt="photo.caption || '图集照片'" loading="lazy" decoding="async" class="h-full w-full object-cover transition hover:scale-105" /></a></div><UButton v-if="hasNext" block class="mt-6" :loading="loadingMore" @click="loadMore">加载更多</UButton></main>
</template>
<script setup lang="ts">
import type { PhotoAlbumVO, PhotoAlbumPageVO, PhotoVO, UserVO } from '~/types'
const route=useRoute();const currentUser=useState<UserVO>('userinfo');const album=ref<PhotoAlbumVO|null>(null);const photos=ref<PhotoVO[]>([]);const page=ref(1);const hasNext=ref(false);const loading=ref(true);const loadingMore=ref(false)
const load=async()=>{try{const res=await useMyFetch<PhotoAlbumPageVO>('/photo/album',{id:Number(route.params.id),page:1,size:60});album.value=res.album;photos.value=res.list;hasNext.value=res.hasNext}finally{loading.value=false}}
const loadMore=async()=>{if(loadingMore.value)return;loadingMore.value=true;try{const res=await useMyFetch<PhotoAlbumPageVO>('/photo/album',{id:Number(route.params.id),page:page.value+1,size:60});photos.value.push(...res.list);page.value++;hasNext.value=res.hasNext}finally{loadingMore.value=false}}
onMounted(load);useHead(()=>({title:album.value?.name?`${album.value.name} · 照片墙`:'图集 · 照片墙',meta:[{name:'description',content:album.value?.description||'照片图集'}]}))
</script>
<style scoped>.eyebrow{color:#88a943;font-size:.68rem;font-weight:700;letter-spacing:.16em;margin-bottom:.35rem}</style>
